version: '2'
services:
  php:
    container_name: skrum-php
    image: php:5.6-fpm
    volumes:
      - ./:/var/local/
      - ./../:/var/local/
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: skm
    ports:
      - "13306:3306"
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
      - ../skrum_database/initdb:/docker-entrypoint-initdb.d
  redis:
    image: redis:3.2.6
    ports:
      - "6379:6379"
