parameters:

    #送信元Eメールアドレス
    from_address: 'service@skrum.jp'

    #カスタマーサポートEメールアドレス
    support_address: 'support@skrum.jp'

    #JWT有効期限（単位：分）
    jwt_exp_minutes: 10080

    #お試しプラン期間（単位：日）
    trial_plan_period: 14

    #1ページあたり表示データ数
    paging_data_number: 20
