services:
    app.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    api.sample_service:
        class: AppBundle\Service\Api\SampleService
        arguments: ['@service_container']
    api.user_setting_service:
        class: AppBundle\Service\Api\UserSettingService
        arguments: ['@service_container']
    api.login_service:
        class: AppBundle\Service\Api\LoginService
        arguments: ['@service_container']
