services:

    app.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.sso_listener:
        class: AppBundle\Listener\SSOListener
        arguments: ['%secret%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority: 255 }

    app.subdomain_listener:
        class: AppBundle\Listener\SubdomainListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority: 0 }

    app.permission_annotation_listener:
        class: AppBundle\Listener\PermissionAnnotationListener
        arguments: ['@annotation_reader']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority: -255 }

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        calls:
            - [ setAnnotationReader, ['@annotation_reader'] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    api.db_existance_logic:
        class: AppBundle\Logic\DBExistanceLogic
        arguments: ['@service_container']

    api.disclosure_logic:
        class: AppBundle\Logic\DisclosureLogic
        arguments: ['@service_container']

    api.okr_achievement_rate_logic:
        class: AppBundle\Logic\OkrAchievementRateLogic
        arguments: ['@service_container']

    api.okr_nested_intervals_logic:
        class: AppBundle\Logic\OkrNestedIntervalsLogic
        arguments: ['@service_container']

    api.okr_operation_logic:
        class: AppBundle\Logic\OkrOperationLogic
        arguments: ['@service_container']

    api.permission_logic:
        class: AppBundle\Logic\PermissionLogic
        arguments: ['@service_container']

    api.post_logic:
        class: AppBundle\Logic\PostLogic
        arguments: ['@service_container']

    api.company_service:
        class: AppBundle\Service\Api\CompanyService
        arguments: ['@service_container']

    api.contract_service:
        class: AppBundle\Service\Api\ContractService
        arguments: ['@service_container']

    api.group_member_service:
        class: AppBundle\Service\Api\GroupMemberService
        arguments: ['@service_container']

    api.group_service:
        class: AppBundle\Service\Api\GroupService
        arguments: ['@service_container']

    api.group_tree_service:
        class: AppBundle\Service\Api\GroupTreeService
        arguments: ['@service_container']

    api.image_upload_service:
        class: AppBundle\Service\Api\ImageUploadService
        arguments: ['@service_container']

    api.login_service:
        class: AppBundle\Service\Api\LoginService
        arguments: ['@service_container']

    api.okr_details_service:
        class: AppBundle\Service\Api\OkrDetailsService
        arguments: ['@service_container']

    api.okr_map_service:
        class: AppBundle\Service\Api\OkrMapService
        arguments: ['@service_container']

    api.okr_operation_service:
        class: AppBundle\Service\Api\OkrOperationService
        arguments: ['@service_container']

    api.okr_service:
        class: AppBundle\Service\Api\OkrService
        arguments: ['@service_container']

    api.okr_setting_service:
        class: AppBundle\Service\Api\OkrSettingService
        arguments: ['@service_container']

    api.payment_service:
        class: AppBundle\Service\Api\PaymentService
        arguments: ['@service_container']

    api.search_service:
        class: AppBundle\Service\Api\SearchService
        arguments: ['@service_container']

    api.timeframe_service:
        class: AppBundle\Service\Api\TimeframeService
        arguments: ['@service_container']

    api.timeline_service:
        class: AppBundle\Service\Api\TimelineService
        arguments: ['@service_container']

    api.user_service:
        class: AppBundle\Service\Api\UserService
        arguments: ['@service_container']

    api.user_setting_service:
        class: AppBundle\Service\Api\UserSettingService
        arguments: ['@service_container']

    batch.achievement_rate_log_service:
        class: AppBundle\Service\Batch\AchievementRateLogService
        arguments: ['@service_container']

    batch.achievement_registration_reminder_email_service:
        class: AppBundle\Service\Batch\AchievementRegistrationReminderEmailService
        arguments: ['@service_container']

    batch.email_sending_service:
        class: AppBundle\Service\Batch\EmailSendingService
        arguments: ['@service_container']

    batch.feedback_target_report_email_service:
        class: AppBundle\Service\Batch\FeedbackTargetReportEmailService
        arguments: ['@service_container']

    batch.member_report_email_service:
        class: AppBundle\Service\Batch\MemberReportEmailService
        arguments: ['@service_container']
