swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/{userId}/top.json:
    get:
      description: ナビゲーション情報取得
      parameters:
        -
          name: userId
          in: path
          type: string
          description: ユーザID
          required: true
      responses:
        200:
          description: ナビゲーション情報
          schema:
            type: object
            properties:
              timeframes:
                type: array
                items:
                  type: object
                  properties:
                    timeframeId:
                      type: integer
                    timeframeName:
                      type: string
                    startDate:
                      type: string
                    endDate:
                      type: string
                    defaultFlg:
                      type: integer
                  required:
                    - timeframeId
                    - timeframeName
                    - startDate
                    - endDate
              teams:
                type: array
                items:
                  type: object
                  properties:
                    groupId:
                      type: integer
                    groupName:
                      type: string
                    imageVersion:
                      type: integer
              departments:
                type: array
                items:
                  type: object
                  properties:
                    groupId:
                      type: integer
                    groupName:
                      type: string
                    imageVersion:
                      type: integer
              company:
                type: object
                properties:
                  companyId:
                    type: integer
                  name:
                    type: string
                  imageVersion:
                    type: integer
              users:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                    name:
                      type: string
                    imageVersion:
                      type: integer
            required:
              - timeframes
              - company
              - users
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
