swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /companies/{companyId}/basics.json?{tfid}:
    get:
      description: 会社目標管理情報取得
      parameters:
        -
          name: companyId
          in: path
          type: string
          description: 会社ID
          required: true
        -
          name: tfid
          in: path
          type: string
          description: タイムフレームID
          required: true
      responses:
        200:
          description: 会社目標管理情報
          schema:
            type: object
            properties:
              company:
                type: object
                properties:
                  companyId:
                    type: integer
                  name:
                    type: string
                  imageVersion:
                    type: integer
                  vision:
                    type: string
                  mission:
                    type: string
                  lastUpdate:
                    type: string
                required:
                  - companyId
                  - name
                  - imageVersion
              okrs:
                type: array
                items:
                  type: object
                  properties:
                    okrId:
                      type: integer
                    okrType:
                      type: string
                    okrName:
                      type: string
                    ownerCompanyId:
                      type: integer
                    ownerCompanyName:
                      type: string
                    ownerCompanyImageVersion:
                      type: integer
                    targetValue:
                      type: integer
                    achievedValue:
                      type: integer
                    unit:
                      type: string
                    achievementRate:
                      type: number
                    status:
                      type: string
                    disclosureType:
                      type: string
                    parentOkr:
                      type: object
                      properties:
                        okrId:
                          type: integer
                        okrName:
                          type: string
                        ownerType:
                          type: string
                        ownerUserId:
                          type: integer
                        ownerUserName:
                          type: integer
                        ownerUserImageVersion:
                          type: integer
                        ownerGroupId:
                          type: integer
                        ownerGroupName:
                          type: integer
                        ownerGroupImageVersion:
                          type: integer
                        ownerCompanyId:
                          type: integer
                        ownerCompanyName:
                          type: integer
                        ownerCompanyImageVersion:
                          type: integer
                      required:
                        - okrId
                        - okrName
                        - ownerType
                    keyResults:
                      type: array
                      items:
                        type: object
                        properties:
                          okrId:
                            type: integer
                          okrName:
                            type: string
                          targetValue:
                            type: integer
                          achievedValue:
                            type: integer
                          unit:
                            type: string
                          achievementRate:
                            type: number
                          ownerType:
                            type: string
                          ownerUserId:
                            type: integer
                          ownerUserName:
                            type: string
                          ownerUserImageVersion:
                            type: integer
                          ownerUserRoleLevel:
                            type: integer
                          ownerGroupId:
                            type: integer
                          ownerGroupName:
                            type: string
                          ownerGroupImageVersion:
                            type: integer
                          ownerGroupType:
                            type: string
                          ownerCompanyId:
                            type: integer
                          ownerCompanyName:
                            type: string
                          ownerCompanyImageVersion:
                            type: integer
                          status:
                            type: string
                          disclosureType:
                            type: string
                          weightedAverageRatio:
                            type: number
                          ratioLockedFlg:
                            type: integer
                        required:
                          - okrId
                          - okrName
                          - targetValue
                          - achievedValue
                          - unit
                          - achievementRate
                          - ownerType
                          - status
                          - disclosureType
                          - weightedAverageRatio
                          - ratioLockedFlg
                  required:
                    - okrId
                    - okrName
                    - ownerCompanyId
                    - ownerCompanyName
                    - ownerCompanyImageVersion
                    - targetValue
                    - achievedValue
                    - unit
                    - achievementRate
                    - status
                    - disclosureType
            required:
              - company
              - okrs
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
