swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs/{okrId}/achievements:
    post:
      description: OKR進捗登録
      parameters:
        -
          name: okrId
          in: path
          type: string
          description: OKRID
          required: true
        -
          name: JsonRequest
          in: body
          description: OKRID、OKR名、OKR詳細、開始日、終了日
          required: true
          schema:
            type: object
            properties:
              achievedValue:
                type: integer
              targetValue:
                type: integer
              post:
                type: string
            required:
              - achievedValue
              - targetValue
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: パラメータ不正
        401:
          description: 認証エラー
        500:
          description: サーバーエラー
