swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /parentobjectives/search.json?{krid}&{q}:
    get:
      description: 紐付け先Objective検索（紐付け先変更時(対象:Key Result)用）
      parameters:
        -
          name: krid
          in: path
          type: string
          description: 紐付け先変更対象のOKRID（キーリザルトのみ）
          required: true
        -
          name: q
          in: path
          type: string
          description: 検索ワード
          required: true
      responses:
        200:
          description: 検索結果
          schema:
            type: object
            properties:
              okrId:
                type: integer
              okrName:
                type: string
              ownerType:
                type: string
              ownerUserId:
                type: integer
              ownerUserName:
                type: string
              ownerGroupId:
                type: integer
              ownerGroupName:
                type: string
              ownerCompanyId:
                type: integer
              ownerCompanyName:
                type: string
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
