swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs/{okrId}/clone.json:
    post:
      description: OKRコピー
      parameters:
        -
          name: okrId
          in: path
          type: string
          description: OKRID
          required: true
        -
          name: JsonRequest
          in: body
          description: コピー先のタイムフレームID
          required: true
          schema:
            type: object
            properties:
              timeframeId:
                type: integer
            required:
              - timeframeId
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
