swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs/{okrId}/close.json:
    put:
      description: OKRクローズ
      parameters:
        -
          name: okrId
          in: path
          type: string
          description: OKRID
          required: true
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
