swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs/{okrId}/details.json:
    get:
      description: OKR詳細取得
      parameters:
        -
          name: okrId
          in: path
          type: string
          description: OKRID
          required: true
      responses:
        200:
          description: OKR詳細
          schema:
            type: object
            properties:
              objective:
                $ref: '#/definitions/Okr'
              parentOkr:
                $ref: '#/definitions/Okr'
              keyResults:
                type: array
                items:
                  $ref: '#/definitions/Okr'
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー

definitions:
  Okr:
    type: object
    properties:
      okrId:
        type: integer
      okrType:
        type: string
      okrName:
        type: string
      okrDetail:
        type: string
      targetValue:
        type: integer
      achievedValue:
        type: integer
      unit:
        type: string
      achievementRate:
        type: number
      ownerType:
        type: string
      ownerUserId:
        type: integer
      ownerUserName:
        type: string
      ownerGroupId:
        type: integer
      ownerGroupName:
        type: string
      ownerCompanyId:
        type: integer
      ownerCompanyName:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      status:
        type: string
      weightedAverageRatio:
        type: number
      ratioLockedFlg:
        type: integer
    required:
      - okrId
      - okrType
      - okrName
      - okrDetail
      - targetValue
      - achievedValue
      - unit
      - achievementRate
      - ownerType
      - startDate
      - endDate
      - status
