swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs/{okrId}/changeowner.json:
    put:
      description: OKR所有者変更
      parameters:
        -
          name: okrId
          in: path
          type: string
          description: OKRID
          required: true
        -
          name: JsonRequest
          in: body
          description: オーナー種別、オーナーユーザID、オーナーグループID、オーナー会社ID
          required: true
          schema:
            type: object
            properties:
              ownerType:
                type: string
              ownerUserId:
                type: integer
              ownerGroupId:
                type: integer
              ownerCompanyId:
                type: integer
            required:
              - ownerType
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
