swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /posts/{postId}/replies:
    post:
      description: リプライコメント
      parameters:
        -
          name: postId
          in: path
          type: integer
          description: リプライ先の投稿ID
          required: true
        -
          name: JsonRequest
          in: body
          description:
          required: true
          schema:
            type: object
            properties:
              post:
                type: string
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: パラメータ不正
        401:
          description: 認証エラー
        500:
          description: サーバーエラー
