swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /posts/{postId}/changedisclosure.json:
    put:
      description: 投稿公開設定変更
      parameters:
        -
          name: postId
          in: path
          type: string
          description: 投稿ID
          required: true
        -
          name: JsonRequest
          in: body
          description: 変更後公開種別
          required: true
          schema:
            type: object
            properties:
              disclosureType:
                type: string
            required:
              - disclosureType
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
