swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /groups/search.json?{q}:
    get:
      description: グループ検索
      parameters:
        -
          name: q
          in: path
          type: string
          description: 検索ワード
          required: true
      responses:
        200:
          description: 検索結果
          schema:
            type: object
            properties:
              groupId:
                type: integer
              groupName:
                type: string
              imageVersion:
                type: integer
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
