swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /groups/{groupId}/members.json?{tfid}:
    post:
      description: グループメンバー追加
      parameters:
        -
          name: groupId
          in: path
          type: string
          description: グループID
          required: true
        -
          name: timeframeId
          in: path
          type: string
          description: タイムフレームID
          required: true
        -
          name: JsonRequest
          in: body
          description: ユーザID
          required: true
          schema:
            type: object
            properties:
              userId:
                type: integer
            required:
              - userId
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              user:
                type: object
                properties:
                  userId:
                    type: integer
                  name:
                    type: string
                  position:
                    type: string
                  achievementRate:
                    type: number
                  lastLogin:
                    type: string
                required:
                  - userId
                  - name
                  - position
                  - achievementRate
              group:
                type: object
                properties:
                  groupId:
                    type: integer
                  groupName:
                    type: string
                  groupType:
                    type: string
                  achievementRate:
                    type: number
                required:
                  - groupId
                  - groupName
                  - achievementRate
            required:
              - user
              - group
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
