swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /groups/{groupId}/paths.json:
    post:
      description: 所属先グループ追加
      parameters:
        -
          name: groupId
          in: path
          type: string
          description: グループID
          required: true
        -
          name: JsonRequest
          in: body
          description: 追加所属先グループパス
          required: true
          schema:
            type: object
            properties:
              groupPathId:
                type: integer
            required:
              - groupPathId
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
