swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /additionalusers/search.json?{gid}&{q}:
    get:
      description: 追加ユーザ検索
      parameters:
        -
          name: gid
          in: path
          type: string
          description: グループID（このグループに所属するメンバー以外を検索）
          required: true
        -
          name: q
          in: path
          type: string
          description: 検索ワード
          required: true
      responses:
        200:
          description: 検索結果
          schema:
            type: object
            properties:
              userId:
                type: integer
              userName:
                type: string
              imageVersion:
                type: integer
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
