swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /okrs.json:
    get:
      description: 目標新規登録
      parameters:
        -
          name: JsonRequest
          in: body
          description: オーナー種別、所有者ID、開始日、終了日、OKR名、OKR詳細、目標値、単位、紐付け先OKRID
          required: true
          schema:
            type: object
            properties:
              targetOkr:
                type: object
                properties:
                  timeframeId:
                    type: integer
                  okrType:
                    type: string
                  ownerType:
                    type: string
                  ownerUserId:
                    type: integer
                  ownerGroupId:
                    type: integer
                  ownerCompanyId:
                    type: integer
                  startDate:
                    type: string
                  endDate:
                    type: string
                  okrName:
                    type: string
                  okrDetail:
                    type: string
                  targetValue:
                    type: integer
                  unit:
                    type: string
                  parentOkrId:
                    type: integer
                  disclosureType:
                    type: string
                required:
                  - okrType
                  - ownerType
                  - startDate
                  - endDate
                  - okrName
                  - okrDetail
                  - targetValue
                  - unit
              parentOkr:
                type: object
                properties:
                  okrId:
                    type: integer
                  achievementRate:
                    type: number
                required:
                  - okrId
                  - achievementRate
            required:
              - targetOkr
              - parentOkr
      responses:
        200:
          description: 登録結果
          schema:
            type: object
            properties:
              okrId:
                type: integer
              okrType:
                type: string
              okrName:
                type: string
              okrDetail:
                type: string
              targetValue:
                type: integer
              achievedValue:
                type: integer
              unit:
                type: string
              achievementRate:
                type: number
              ownerType:
                type: string
              ownerUserId:
                type: integer
              ownerUserName:
                type: string
              ownerUserImageVersion:
                type: integer
              ownerGroupId:
                type: integer
              ownerGroupName:
                type: string
              ownerGroupImageVersion:
                type: integer
              ownerCompanyId:
                type: integer
              ownerCompanyName:
                type: string
              ownerCompanyImageVersion:
                type: integer
              startDate:
                type: string
              endDate:
                type: string
              parentOkrId:
                type: integer
              status:
                type: string
              disclosureType:
                type: string
              weightedAverageRatio:
                type: number
              ratioLockedFlg:
                type: integer
            required:
              - okrId
              - okrType
              - okrName
              - okrDetail
              - targetValue
              - achievedValue
              - unit
              - achievementRate
              - ownerType
              - startDate
              - endDate
              - status
              - disclosureType
              - ratioLockedFlg
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
