swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/pagesearch.json?{q}&{p}:
    get:
      description: ユーザ検索（ページング）
      parameters:
        -
          name: q
          in: paths
          type: string
          description: 検索ワード
          required: true
        -
          name: p
          in: paths
          type: string
          description: 要求ページ
          required: true
      responses:
        200:
          description: グループ検索結果
          schema:
            type: object
            properties:
              count:
                type: integer
              results:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                    userName:
                      type: string
                    roleAssignmentId:
                      type: integer
                    roleLevel:
                      type: integer
                    lastLogin:
                      type: string
                  required:
                    - userId
                    - userName
                    - roleAssignmentId
                    - roleLevel
                    - lastLogin
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
