swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /groups/pagesearch.json?{p}&{q}:
    get:
      description: グループ検索（ページング）
      parameters:
        -
          name: p
          in: paths
          type: string
          description: 要求ページ
          required: true
        -
          name: q
          in: paths
          type: string
          description: 検索ワード
          required: false
      responses:
        200:
          description: グループ検索結果
          schema:
            type: object
            properties:
              count:
                type: integer
              results:
                type: array
                items:
                  type: object
                  properties:
                    groupId:
                      type: integer
                    groupName:
                      type: string
                    imageVersion:
                      type: integer
                    groupType:
                      type: string
                  required:
                    - groupId
                    - groupName
                    - imageVersion
                    - groupType
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
