swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /groups.json:
    post:
      description: グループ新規登録
      parameters:
        -
          name: JsonRequest
          in: body
          description: グループ名、グループ種別、所属先グループのグループツリーID
          required: true
          schema:
            type: object
            properties:
              groupName:
                type: string
              groupType:
                type: string
              groupTreeId:
                type: integer
            required:
              - groupName
              - groupType
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
