swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /companies/{companyId}.json:
    get:
      description: 会社基本情報取得
      parameters:
        -
          name: companyId
          in: path
          type: string
          description: 会社ID
          required: true
      responses:
        200:
          description: 会社基本情報
          schema:
            type: object
            properties:
              name:
                type: string
              vision:
                type: string
              mission:
                type: string
            required:
              - companyName
              - vision
              - mission
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
