swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /companies/{companyId}.json:
    put:
      description: 会社基本情報変更
      parameters:
        -
          name: companyId
          in: path
          type: string
          description: 会社ID
          required: true
        -
          name: JsonRequest
          in: body
          description: 会社名、ヴィジョン、ミッション
          required: true
          schema:
            type: object
            properties:
              companyName:
                type: string
              vision:
                type: string
              mission:
                type: string
            required:
              - companyName
              - vision
              - mission
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
