swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /timeframes.json:
    post:
      description: タイムフレーム追加
      parameters:
        -
          name: JsonRequest
          in: body
          description: タイムフレーム名、開始日、終了日
          required: true
          schema:
            type: object
            properties:
              timeframeName:
                type: string
              startDate:
                type: string
              endDate:
                type: string
            required:
              - timeframeName
              - startDate
              - endDate
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              timeframeName:
                type: string
              startDate:
                type: string
              endDate:
                type: string
            required:
              - timeframeName
              - startDate
              - endDate
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
