swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /companies/{companyId}/timeframedetails.json:
    get:
      description: タイムフレーム詳細一覧取得
      parameters:
        -
          name: companyId
          in: path
          type: string
          description: 会社ID
          required: true
      responses:
        200:
          description: タイムフレーム一覧
          schema:
            type: array
            items:
              type: object
              properties:
                timeframeId:
                  type: integer
                timeframeName:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
                defaultFlg:
                  type: integer
              required:
                - timeframeId
                - timeframeName
                - startDate
                - endDate
                - defaultFlg
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
