swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/{userId}/changeemailsettings.json:
    put:
      description: メール配信設定
      parameters:
        -
          name: userId
          in: path
          type: string
          description: ユーザID
          required: true
        -
          name: JsonRequest
          in: body
          description: メール配信設定変更
          required: true
          schema:
            type: object
            properties:
              okrAchievement:
                type: integer
              okrTimeline:
                type: integer
              oneOnOne:
                type: integer
              okrDeadlineReminder:
                type: integer
              okrReminder:
                type: integer
              reportMemberAchievement:
                type: integer
              reportGroupAchievement:
                type: integer
              reportFeedbackTarget:
                type: integer
              serviceNotification:
                type: integer
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
