swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /companies/{companyId}/payments.json:
    get:
      description: 請求情報取得
      parameters:
        -
          name: companyId
          in: path
          type: string
          description: 会社ID
          required: true
      responses:
        200:
          description: 請求情報
          schema:
            type: object
            properties:
              paymentId:
                type: integer
              paymentDate:
                type: string
              status:
                type: string
              chargeAmount:
                type: number
            required:
              - paymentId
              - paymentDate
              - status
              - chargeAmount
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
