swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/{userId}/changepassword.json:
    put:
      description: パスワード変更
      parameters:
        -
          name: userId
          in: path
          type: string
          description: ユーザID
          required: true
        -
          name: JsonRequest
          in: body
          description: 現在のパスワード、新パスワード
          required: true
          schema:
            type: object
            properties:
              currentPassword:
                type: string
              newPassword:
                type: string
            required:
              - currentPassword
              - newPassword
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              result:
                type: string
            required:
              - result
        400:
          description: JSONスキーマ不正
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
