swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/{userId}/reports.json:
    post:
      description: 日報/進捗報告送信
      parameters:
        -
          name: userId
          in: paths
          type: string
          description: ユーザID
          required: true
        -
          name: JsonRequest
          in: body
          description: 1on1種別、報告日、宛先、紐付けOKRID、本文
          required: true
          schema:
            type: object
            properties:
              oneOnOneType:
                type: string
              reportDate:
                type: string
              to:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
              okrId:
                type: integer
              body:
                type: string
            required:
              - oneOnOneType
              - reportDate
              - body
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              oneOnOneId:
                type: integer
              oneOnOneType:
                type: string
              senderUserId:
                type: integer
              senderUserName:
                type: string
              senderUserImageVersion:
                type: integer
              toNames:
                type: string
              lastUpdate:
                type: string
              partOfText:
                type: string
              readFlg:
                type: integer
            required:
              - oneOnOneId
              - oneOnOneType
              - senderUserId
              - senderUserName
              - senderUserImageVersion
              - lastUpdate
              - partOfText
              - readFlg
        400:
          description: JSONスキーマ不正
        401:
          description: 認証エラー
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
