swagger: '2.0'

info:
  version: "1.0.0"
  title: skrum.jp
schemes:
  - https
produces:
  - application/json
basePath: /v1

paths:
  /users/{userId}/oneonones.json?{oootype}&{before}:
    get:
      description: 1on1送受信履歴取得
      parameters:
        -
          name: userId
          in: paths
          type: string
          description: ユーザID
          required: true
        -
          name: oootype
          in: paths
          type: string
          description: 1on1種別
          required: true
        -
          name: before
          in: paths
          type: string
          description: 取得基準日時
          required: false
      responses:
        200:
          description: 1on1送受信履歴
          schema:
            type: object
            properties:
              oneOnOneId:
                type: integer
              oneOnOneType:
                type: string
              senderUserId:
                type: integer
              senderUserName:
                type: string
              imamgeVersion:
                type: integer
              toNames:
                type: string
              intervieweeUserName:
                type: string
              lastUpdate:
                type: string
              partOfText:
                type: string
              readFlg:
                type: integer
            required:
              - oneOnOneId
              - oneOnOneType
              - senderUserId
              - senderUserName
              - imamgeVersion
              - lastUpdate
              - partOfText
              - readFlg
        400:
          description: JSONスキーマ不正
        401:
          description: 認証エラー
        409:
          description: 排他エラー
        500:
          description: サーバーエラー
