swagger: '2.0'

info:
  version: "1.0.0"
  title: skrumAPI
host: # 保留
schemes:
  - https
produces:
  - application/json
tags:
  - name: skrum
basePath: /v1

paths:
  /login:
    post:
      tags:
        - skrum
      description: ログイン
      parameters:
        -
          name: X-Session
          in: header #sessionはない時があるのでheaderに入れて送ってほしいです
          type: string
          description: sessionがある場合は取得
          default: login-session #適当です
        -
          name: user_name
          in: body
          required: true #必須
          type: string
          example: skrum.taro
        -
          name: password
          in: body
          required: true #必須
          type: string
          example: password123
      responses:
        200:
          description: 成功
          schema:
            type: object
            properties:
              company_information:
                type: object #返り値要相談
            required:
              - company_information
        400:
          description: パラメータ不正
        401:
          description: 認証エラー
        404:
          description: 認証エラー（該当なし）
        500:
          description: サーバーエラー
          schema:
            $ref: '#/definitions/500_error'


definitions:
  500_error:
    type: object
    properties:
      errors:
        type: object
        properties:
          errorMessage:
            type: string
            example: "サーバーへの接続に失敗しました。時間をおいて再度お試しください。"

