version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: skm
    ports:
      - "13306:3306"
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
      - ../skrum_database/initdb:/docker-entrypoint-initdb.d
  redis:
    image: redis:3.2.6
    ports:
      - "26379:6379"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../:/var/www/html
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    container_name: skrum-nginx
  php:
    build: ./php-fpm
    container_name: skrum-php
    image: php:5.6-fpm
    ports:
      - "8000:80"
      - "3000:3000"
    volumes:
      - ./:/var/local/
      - ./../:/var/www/html
    links:
      - db
