imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../src/AppBundle/Resources/config/parameters.yml }
    - { resource: ../../src/AppBundle/Resources/config/services.yml }
    - { resource: ../../src/AppBundle/Resources/translations/messages.ja.yml }
    - { resource: ../../src/AppBundle/Resources/translations/validators.ja.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ja
    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        logging: true
        profiling: true

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            soft-deleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        metadata_cache_driver: redis
        #result_cache_driver: redis
        query_cache_driver: redis

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: ja_JP
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: file
        path: %kernel.root_dir%/spool

# FOSRestBundle Configuration
fos_rest:
    view:
        view_response_listener: force

# NelmioCorsBundle Configuration
nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^http://[a-z0-9-]+\.localhost:3000']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']

# SncRedisBundle Configuration
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%redis_dsn_default%"
        cache:
            type: phpredis
            alias: cache
            dsn: "%redis_dsn_cache%"
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: [default]
        query_cache:
            client: cache
            entity_manager: default

# SeferovAwsBundle Configuration
seferov_aws:
    credentials:
        key: AWS_KEY
        secret: AWS_SECRET
    region: ap-northeast-1
    services:
        s3:
            credentials:
                key: AKIAJ6E4IW257QWV3Z4Q
                secret: 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
            region: ap-northeast-1
            version: latest
