imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/application.log"
            level: debug
            channels: [!event, !doctrine, !security, !snc_redis]
        alert:
            type: stream
            path: "%kernel.logs_dir%/alert.log"
            level: alert
            channels: [!event, !doctrine]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/sql.log"
            level: debug
            channels: [doctrine]
        console:
            type: console
            channels: [!event, !doctrine]

swiftmailer:
    delivery_addresses: ['skrum.development@gmail.com']

# NelmioCorsBundle Configuration
nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^http:[/][/][a-z0-9-]+\.localhost:3000']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        '^/v1/preregister':
            origin_regex: true
            allow_origin: ['^http:[/][/]localhost:3000']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST']
