imports:
    - { resource: config_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: true
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    delivery_addresses: ['skrum.development@gmail.com']

# NelmioCorsBundle Configuration
nelmio_cors:
    paths:
        '^/v1/preregister.json':
            origin_regex: true
            allow_origin: ['^https:[/][/]skrum-stg.work']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST']
        '^/':
            origin_regex: true
            allow_origin: ['^https:[/][/][a-z0-9-]+\.skrum-stg.work']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
