imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console

# NelmioCorsBundle Configuration
nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^https:[/][/][a-z0-9-]+\.skrum.jp']
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
