app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app_rest_sample:
#    resource: "@AppBundle/Controller/Api/SampleController.php"
#    type: rest
#    prefix: /api

skrum_login:
    path: /login
    resource: "@AppBundle/Controller/LoginController.php"
    type: rest
    prefix: /api
