app:
    resource: '@AppBundle/Controller/'
    type: annotation
    host: "{subdomain}.localhost"
    prefix: /api

login:
    path: /api/preregister.{_format}
    defaults: { _controller: AppBundle:Api\Login:preregister }
    methods: [POST]
    host: localhost
