parameters:
    sample_parmeter_controller: 'サンプルパラメータ in Controller'
    sample_parmeter_service: 'サンプルパラメータ in Service'

services:
    api.sample_service:
        class: AppBundle\Service\Api\SampleService
        arguments: ['@service_container']
